### ISSUE TITLE
Make rules links actual HTML links

### ISSUE THREAD

**Issue by Samiii-AP** [requestly/requestly#305] opened 2023-02-20 16:32 UTC
In the interface, please use actual HTML links (<a href>) to allow us to open it in a new tab.

Currently, in HTTP Rules, the rules are links but impossible to open them in new tabs. This is a problem when we want to check the coherence of their content for example.

**Comment by malay5** [comment] 2023-06-03 10:16
Could you please provide more description of what is required?

**Comment by lazyvab** [comment] 2023-06-03 11:07
@malay5 When you are on the Rules list page, the name of rules appear as links. But you cannot open a rule in new tab using `Cmd+click` or right-click and `Open Link in New Tab`. 

This is most likely because the link is not an HTML link `<a>` and an on-click listener is attached using JS.

**Comment by wrongsahil** [comment] 2023-08-23 20:04
Duplicate of #770

**Closed by wrongsahil** 2023-08-23 20:04 UTC
Labels: enhancement
