### ISSUE TITLE
Mime Type Error while replacing CSS and JS files Requestly returns content-type as text/html

### ISSUE THREAD

**Issue by mankondavivek** [requestly/requestly#35] opened 2018-05-17 08:54 UTC
![screenshot from 2018-05-17 14-17-33](https://user-images.githubusercontent.com/34041198/40166913-55ee859c-59dd-11e8-9a89-5c02d0707386.png)
Requestly returns text/html as content type header for both css and js. The browser throws an error and the request is cancelled.

**Comment by sachinjain024** [comment] 2018-05-17 08:58
Thanks @mankondavivek for logging the issue. Can you please tell the exact steps you followed so that we can reproduce the issue and fix it.

**Comment by sachinjain024** [comment] 2018-07-24 12:38
Closing this issue. Please reopen if you want to continue the discussion.

**Comment by borislit** [comment] 2022-05-21 15:58
@sachinjain024   Hi, ive actually encountered that issue too.
Ive used the "Replace rule" to replace path of the of the path (lets say https://www.foobarcdn.com/dev) with https://localhost:3031.
When i refresh the page, Im getting the files blocked by CORB, because all of the js/css files receive content-type of text/html

**Closed** 2022-12-13 09:50 UTC
Labels: feat:redirect_rule
