### ISSUE TITLE
bug: Query Param and Request headers could not modified for Requestly Mock APIs

### ISSUE THREAD

**Issue by lazyvab** [requestly/requestly#272] opened 2023-01-16 17:59 UTC
### Describe your issue?

I created a mock API in Requestly and want to add a new query parameter and a request header on that.
But this could not be done on the URL obtained from the Mock API page.

### Repro steps

N/A

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

Chrome

### Requestly Version

23.1.4

**Comment by wrongsahil** [comment] 2023-01-17 06:33
Even if users pass new query params or headers, there won’t be any difference in the response right now.

This will makes sense when we have templating in mocks and then we can make smart decisions in mock based on headers and query params.

**Comment by lazyvab** [comment] 2023-01-17 06:36
The mock API currently redirects to another endpoint and I guess if the user's code depends on request headers or query params, s(he) may use the redirect URL instead of original URL. 
@wrongsahil Is it a correct understanding?

**Comment by sachinjain024** [comment] 2023-01-17 06:57
@lazyvab Although technically you're right. Since Mock Server is doing a redirect to a different URL, adding any modifications may not handled in the Mock server implementation but also curious to know what are we trying to achieve here?

**Comment by wrongsahil** [comment] 2023-01-17 07:10
Yeah. Modification on redirected url should work. In Mock Picker, redirected url is picked only.

**Comment by lazyvab** [comment] 2023-01-17 07:14
@sachinjain024 I don't have a strong use-case as of now. Like @wrongsahil said, it might make sense to do in future when we support dynamic response from Mock API. 
This was actually raised by a user who was creating Requestly rules on the mock API endpoint and didn't see the rules getting applied. But he didn't have a valid use-case either.

I think we can close as "Won't fix".

**Comment by wrongsahil** [comment] 2023-01-17 07:16
Only use case i can think of is response header modifications. But that can also be fixed by changing response headers directly in the mock

**Comment by wrongsahil** [comment] 2023-08-24 10:30
Duplicate of #627

**Closed by wrongsahil** 2023-08-24 10:30 UTC
Labels: type: bug
