### ISSUE TITLE
When can I support the Mac with the m1 chip?

### ISSUE THREAD

**Issue by beergold** [requestly/requestly#506] opened 2023-04-11 05:54 UTC
When can support the Mac with the m1 chip?

**Comment by wrongsahil** [comment] 2023-04-24 05:40
Closing this as already desktop app supports M1 chip.

**Closed by wrongsahil** 2023-04-24 05:40 UTC

**Comment by beergold** [comment] 2023-04-24 05:46
Yes, although it can work on m1, the architecture is x86 instead of arm, so the rosetta needs to work, causing the application to load very Catton, hoping to adapt as soon as possible.

**Comment by wrongsahil** [comment] 2023-08-02 04:29
Duplicate of #860
