### ISSUE TITLE
bug: Requestly rules no longer work in Mac Chrome/Safari after updating to Ventura 13.0.1 (only works with Chrome extension)

### ISSUE THREAD

**Issue by Anyclip** [requestly/requestly#269] opened 2023-01-11 08:17 UTC
### Describe your issue?

After updating my MacOS to **Ventura 13.0.1** I noticed that the Requestly rules no longer work via Requestly desktop-app 1.4.19.  However, if I use Requestly via the Mac Chrome extension then Requeslty rules work as expected.  So now I can't perform any tests on Mac Safari due to the fact that no Requestly rules are working correctly.  It appears that simply opening the Requesty desktop app (without even enabling any Requestly rules) on Mac Safari prevents from receiving expected events such as ty=**arq**.  This issue only started to occur when I upgraded my MacOS to **Ventura 13.0.1**  Issue does not occur if I use Requestly Mac Chrome extension. Please assist ASAP!

### Repro steps

1) Open https://www.wordhippo.com/what-is/the-meaning-of-the-word/hope.html in Mac Safari and notice that ty=arq events are being received when the Requestly desktop app is not enabled.

![image](https://user-images.githubusercontent.com/92794119/211752763-07e59ee4-4643-4d8c-afb2-cb095a2286d8.png)

2) Now enable the Requestly desktop app (with/without Requestly rules enabled) and notice that no ty=arq events are received.
![image](https://user-images.githubusercontent.com/92794119/211753269-bf9635f9-eedc-488e-b5a3-19496b7e9837.png)

The same issue occurs in Mac Chrome however issue does not occur if Requestly chrome extension is used instead of Requestly desktop app.

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOS (Ventura 13.0.1)  Safari 16.1, Chrome 108.0.5359.124

### Requestly Version

1.4.19

**Comment by sachinjain024** [comment] 2023-01-11 08:20
Hey @Anyclip Thanks a lot for reporting this issue. Can you please launch a new Chrome Instance from the desktop app and tell us if the issue persists in Chrome launched from desktop app as well?

Or Is this Safari specific? This will help us troubleshoot the issue faster.

**Comment by wrongsahil** [comment] 2023-01-11 08:46
Hey @Anyclip. I tried to go on the above link but i can see all the requests `ty=arq`. I'm also on MacOS (Ventura 13.0.1)

I tried applying a rule. That seem to be working fine too
![ty=arq](https://user-images.githubusercontent.com/16779465/211758904-82b506f7-23c6-4f6a-9cc1-63bb183b1f95.png)

Can you try with enabling `disable caches` once. Here's how you enable it
![Screenshot 2023-01-11 at 2 00 47 PM](https://user-images.githubusercontent.com/16779465/211759575-d1f92b19-8596-4a18-90bd-4a845ee8d774.png)

**Comment by Anyclip** [comment] 2023-01-11 11:10
@wrongsahil Per your request I enabled disable caches once on Mac Safari and now when I enable the Requestly desktop app (without any Requestly rules enabled) I do receive the ty=arq events (as expected....Thank you!).  However, if I enable these 3 Requestly rules https://app.requestly.io/rules/#sharedList/1673433576722-Sagi-shared-list-1-11-2023 then the ty=arq events no longer appear in BOTH Safari and Mac Chrome.  However, if I enable the same 3 Requestly rules via the Mac Chrome Requestly extension and/or in Window Chrome, Edge and/or Firefox I do receive ty=arq events.   

So @sachinjain024  this occurs even when I launch a new Chrome instance from the Requestly desktop app on my Mac,  Therefore the issue appears to be solely Mac related for both Mac Safari and Mac Chrome browsers.  Again this issue began to occur only after I updated MacOS to Ventura 13.0.1.

**Comment by wrongsahil** [comment] 2023-01-13 05:52
Hey @Anyclip. I tried with the above rules too. I can see that all the requests are still coming. But they seem to take longer time that usual when desktop app is connected. Can you try waiting for sometime after refreshing the page and check if the requests are coming or not?

I think the problem is with desktop app slowing down the network. We already have a issue logged for this #260 . We'll try to pick this up on priority

**Comment by Anyclip** [comment] 2023-02-13 09:56
@wrongsahil @sachinjain024 Even after the last Requestly update (1.4.21) the issue still persists (unable to receive any ty=arq events) on Mac whenever Requestly desktop app is open on Mac. Works fine when using Requestly browser extension on Mac Chrome however since there is no similar browser extension on Mac Safari, we are unable to conduct the required tests on Mac Safari.  Any other suggestions to overcome this critical issue?

**Comment by sachinjain024** [comment] 2023-02-13 11:31
Hey, @Anyclip Thanks for the revert here. I tried this on my end but we couldn't reproduce this either. I'd suggest having a call and taking this forward. Let me ping you on Community slack (or the shared slack channel we have)

**Comment by Anyclip** [comment] 2023-02-14 08:03
@sachinjain024  I understand that on your end the issue is not producible.  However, I don't understand why on my end it is producible as soon as the Requestly desktop application is opened on Mac (even without enabling a single Requestly rule)?  On the other hand, if I close the Requestly desktop application on Mac and use the Requestly Chrome browser extension instead then no issues are encountered and everything works fine.  This leads me to believe that the source of the issue is likely the Requestly desktop app itself.

**Comment by Anyclip** [comment] 2023-02-14 10:17
@sachinjain024 I updated this morning my Mac to macOS **Ventura 13.2.1**, Mac **Safari 16.3**, **Requestly 1.4.22** and the issue still occurs. However, when I search for **ty=err** in the Network dev tools tab I receive the following error message '_**_lre - failed loading ad manager script | ad block detected_**_' whenever the Requestly desktop app is open on Mac (even without any Requestly rules enabled)
![image](https://user-images.githubusercontent.com/92794119/218705183-a70d90a8-66df-4c95-950f-4de256885e25.png)

Hope this additional info can point you in the right direction in resolving this critical and urgent issue.

**Comment by wrongsahil** [comment] 2023-02-14 10:19
@Anyclip Are you available for quick call right now?

**Comment by Anyclip** [comment] 2023-02-14 11:45
@wrongsahil Available now.  Please send a Google Meet invite when available.

**Comment by sachinjain024** [comment] 2023-03-03 11:10
@Anyclip I tried this multiple times even upgraded both of my machines to Ventura but still this looks to work fine at my end.

<img width="2187" alt="image" src="https://user-images.githubusercontent.com/3108399/222705607-4dfdeabd-7304-4d18-8955-7f174dd99b27.png">

<img width="287" alt="image" src="https://user-images.githubusercontent.com/3108399/222705670-d8efee16-e237-4f47-96b2-19e34966fa2f.png">

Could you please ask one of your colleagues to try this at their end? Could this be specific to location? We're based out of India.

**Comment by wrongsahil** [comment] 2023-08-24 10:32
@Anyclip Closing this for now. Please reopen it incase you are still facing this issue

**Closed by wrongsahil** 2023-08-24 10:32 UTC
Labels: type: bug, cant_reproduce, desktop_app
