### ISSUE TITLE
bug: Unable to use requestly rules in new google chrome browser version 119.x.x.x

### ISSUE THREAD

**Issue by rishikesh-parspec** [requestly/requestly#1220] opened 2023-11-20 09:41 UTC
### Describe your issue?

We have been employing the requestly string replace rule; however, in the past few days, requestly has ceased to function

### Repro steps

Same as above

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOs ventura 13.1, chrome version 119.x.x

### Requestly Version

23.11.8

**Comment by kumarlovish** [comment] 2023-11-20 10:12
When we are using requestly to replace the string, in the current chrome version 119+ version it is not sending Authorisation header in the API call which fails the API and server returns 401.

**Comment by nafees87n** [comment] 2024-02-18 15:40
Duplicate of #1208 
Closing this issue

**Closed by nafees87n** 2024-02-18 15:40 UTC
Labels: duplicate
