### ISSUE TITLE
Every time I try recording a session on web.pennyapp.com I get "Something went wrong. Please contact the support."

### ISSUE THREAD

**Issue by gecsp** [requestly/requestly#256] opened 2022-12-20 02:07 UTC
## Expected Behavior

The session records.

## Current Behavior

I get an error message: Something went wrong. Please contact the support.

## Steps to Reproduce

1.  Set Session Recording configuration to URL CONTAINS pennyapp.com

2.  Navigate to web.pennyapp.com.  Click Don't have an account?  Create One.

3.  Enter email, name, password and click create account.

4. Click Requestly Extention icon.  Click View Recording.

6.  Get taken to https://app.requestly.io/sessions/draft/58028506

7.  See error message: Something went wrong. Please contact the support.

## Possible Solution (Not obligatory)

N/A

## Your Environment

- Operating System and version :  Mac OS Ventura
- Extension Version :  22.12.6
- Desktop App Version :  N/A

**Comment by rohanmathur91** [comment] 2022-12-20 04:40
Hey @gecsp, thanks for opening the issue, we are looking into it.

**Comment by lazyvab** [comment] 2022-12-20 13:45
@gecsp Thanks for reporting the issue. 

I found a bug where if there is a network request on a website where the request body is a form data instead of JSON, the serialization fails and the session details cannot be opened.

The fix is expected to be in the browser extension which usually takes a couple of days to get deployed.
Meanwhile, your patience is greatly appreciated.

**Comment by gecsp** [comment] 2022-12-20 17:53
@lazyvab That's fantastic, thank you!

**Comment by lazyvab** [comment] 2022-12-28 06:43
@gecsp Thanks for waiting. The fix is now available in version `22.12.27`.
Please go to chrome://extensions/ and click `Update` button. 

The new version should reflect on the Requestly card:
<img width="300" alt="Screenshot 2022-12-28 at 12 06 13 PM" src="https://user-images.githubusercontent.com/6367566/209769187-187b7c9f-25db-4faa-9ed6-6130f8b28f3b.png">

Otherwise, the update happens automatically on browser restart.

Please confirm if the issue is fixed on your end so we can close the ticket.

**Comment by lazyvab** [comment] 2023-01-13 10:04
@gecsp We didn't hear back from you. Hope it's working fine now. 

Closing the issue. Please feel free to reopen or log a new ticket.

**Closed by lazyvab** 2023-01-13 10:04 UTC
Labels: bug, feat:session_recording
