### ISSUE TITLE
Requestly causes Zendesk to fail to load

### ISSUE THREAD

**Issue by nbolton** [requestly/requestly#1782] opened 2024-06-07 03:37 UTC
### Describe your issue?

When I try to use Zendesk with Requestly enabled, I get an error in Zendesk.

> Zendesk Support could not be loaded due to an error.
> Please try refreshing and contact our Customer Support team if the problem persists.

*I know*, this is arguably a Zendesk bug, but perhaps someone here can help me understand why Requestly breaks Zendesk so I can explain to the Zendesk team exactly what's going wrong. I have opened a ticket with Zendesk but I'm not expecting them to say anything other than "Disable the Requestly extension"

Zendesk browser log when Requestly is enabled (unfortunately not very telling):

```
dashboard:1 Third-party cookie will be blocked. Learn more in the Issues tab.
Navigated to https://symless.zendesk.com/agent/dashboard
dashboard:1 The keyword 'searchfield-cancel-button' used on the 'appearance' property was deprecated and has now been removed. It will no longer have any effect.
Navigated to https://symless.zendesk.com/agent/dashboard
dashboard:1 The keyword 'searchfield-cancel-button' used on the 'appearance' property was deprecated and has now been removed. It will no longer have any effect.
dashboard:1 
        
        
       POST https://symless.zendesk.com/agent/dashboard 503 (Service Unavailable)
Navigated to https://symless.zendesk.com/agent/dashboard
```

Is there a way to enable verbose logging in Requestly so I can understand why Requestly might be interfering with Zendesk?

### Repro steps

1. Login to Zendesk successfully
2. Enable the Requestly extension
3. Refresh the page
4. Zendesk error occurs
5. Disable the Requestly extension
6. Refresh the page
7. Zendesk error goes away and it works fine again

### What Requestly tool were you using?

- [X] Extension
- [ ] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

125.0.6422.141

### Requestly Version

24.5.27

### Error screenshot

![Screenshot from 2024-06-07 04-07-11](https://uploads.linear.app/fb4f8e41-5735-4034-803e-a097bb4ad79b/7440b3db-21a2-4f3f-8947-345063fc34eb/f03fe5c4-6bc2-444f-a208-c2170f4b440e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2ZiNGY4ZTQxLTU3MzUtNDAzNC04MDNlLWEwOTdiYjRhZDc5Yi83NDQwYjNkYi0yMWEyLTRmM2YtODk0Ny0zNDUwNjNmYzM0ZWIvZjAzZmU1YzQtNmJjMi00NDRmLWEyMDgtYzIxNzBmNGI0NDBlIiwiaWF0IjoxNzE3NzQ4NDA5LCJleHAiOjMzMjg4MzA4NDA5fQ.0XxldOBume8l8PnqO_YAe0wTB6BE7F1YxGbX6l5J0qc)

**Comment by wrongsahil** [comment] 2024-06-07 04:55
Thanks for pointing this out, @nbolton! I've also reproduced the issue. I'll investigate further and update you soon.

**Comment by nbolton** [comment] 2024-06-07 08:33
> Thanks for pointing this out, @nbolton! I've also reproduced the issue. I'll investigate further and update you soon.

Awesome, I'd love to do a bit of digging too, is there a guide for things like increasing the log level, etc?

**Comment by wrongsahil** [comment] 2024-06-07 09:01
Not at the moment. We've only some logs available in the extension service worker.

We recently shipped a new version #1690 which contains a lot of architectural changes. That might have caused this issue.
This seems to be working fine in older MV2 versions.

**Comment by wrongsahil** [comment] 2024-06-07 09:03
One weird thing i see is that the document calls get upgraded from GET to POST automatically which seems to break Zendesk

<img width="2024" alt="CleanShot 2024-06-07 at 14 32 49@2x" src="https://github.com/requestly/requestly/assets/16779465/cc49b065-b6f2-4385-975f-086cca5fa5c6">

**Comment by wrongsahil** [comment] 2024-06-07 10:32
https://github.com/requestly/requestly/blob/b4fe38d81fe0544de6fdfcb5558d66443dfd1ad2/browser-extension/mv3/src/client-scripts/ajaxRequestInterceptor.js#L508-L512

Seems to be related XHR interceptor we inject for Response Rule interception. On commenting this, everything works fine. Working on a fix right now

**Comment by nbolton** [comment] 2024-06-14 07:37
> Working on a fix right now

Awesome debugging. Good luck.

**Comment by wrongsahil** [comment] 2024-06-20 11:37
Did some more debugging. It seems to be happening due to the await in this line of code
https://github.com/requestly/requestly/blob/024a7d1977a85b67f6b53e9fb39e8fbf8e1c7006/browser-extension/mv3/src/page-scripts/ajaxRequestInterceptor/xhr.js#L324

**Comment by wrongsahil** [comment] 2024-07-03 10:58
Hey @nbolton , Can you try out this beta build https://chromewebstore.google.com/detail/requestly-intercept-modif/hflhkgcfclhibpldaeppcmcnfkkndmhf?authuser=0&hl=en

As this is beta track, this is not that stable and might contain some other bugs. So please use this only for sometime until we fix the issue in prod

**Comment by edhgoose** [comment] 2024-07-03 15:33
@wrongsahil - we're suffering from the same problem. I've installed your beta version and no longer have the issue.

Thank you!

**Comment by wrongsahil** [comment] 2024-07-08 06:39
Hey @nbolton @edhgoose . v24.7.7 is available in the chrome store now. Can you please manually update the extension using these [steps](https://developers.requestly.com/guides/update-requestly-extension/) and see if this issue still exists or not.

**Comment by edhgoose** [comment] 2024-07-09 18:55
Thanks @wrongsahil - it seems it's working fine for me now. I've got the updated version and will report back if I have any further problems.

**Comment by wrongsahil** [comment] 2024-07-10 12:37
Really happy to know everything is working fine now :D
Closing this issue for now. Feel free open it if you face the issue again.

**Closed by wrongsahil** 2024-07-10 12:37 UTC
Labels: type: bug, issue

**Comment by nbolton** [comment] 2024-07-15 15:31
> v24.7.7

Works perfectly with Zendesk, thank you! :+1:
