### ISSUE TITLE
bug: Close button should be on the top right of the request pane in the traffic inspector

### ISSUE THREAD

**Issue by echo-sg** [requestly/requestly#623] opened 2023-05-18 06:43 UTC
### Describe your issue?

The close button (X) on the request pane currently appear on the top left and should ideally be on the top right. The position needs to be changed.

<img width="1440" alt="close button issue request pane" src="https://github.com/requestly/requestly/assets/56088056/247515aa-ddc6-44d1-9c45-3962b5eb6eeb">

Difficulty: Medium

### Repro steps

1. Open the Requestly Desktop App.
2. Connect any app from the 'Connect Apps' modal. Traffic interception would start for that particular app.
3. From the traffic table, click on any request to open the request pane

### What Requestly tool were you using?

- [ ] Extension
- [X] Desktop-App
- [ ] Android SDK
- [ ] Selenium

### Your Environment

MacOS

### Requestly Version

1.5.1

**Comment by echo-sg** [comment] 2023-05-19 06:51
Yeah that would be great! Assigning you both the issues @tarunsamanta2k20.

**Comment by tarunsamanta2k20** [comment] 2023-05-20 12:38
@echo-sg is this issue for your requestly desktop repo or requestly repo? 

As I can see this issue is related to requestly repo but how to build as a desktop app, it's only working in browser mode.

**Comment by tarunsamanta2k20** [comment] 2023-05-20 12:39
@echo-sg although I have extension installed and running. But how to intercept http request in browser mode?

**Comment by sachinjain024** [comment] 2023-05-20 15:20
@tarunsamanta2k20 Network Inspector is only available in the desktop app. @nsrCodes @wrongsahil -- Have we shared the steps to build & run desktop app locally?

**Comment by tarunsamanta2k20** [comment] 2023-05-20 15:24
> @tarunsamanta2k20 Network Inspector is only available in the desktop app. @nsrCodes @wrongsahil -- Have we shared the steps to build & run desktop app locally?

@sachinjain024 is this issue related to requestly repo or requestly desktop app repo?

**Comment by sashaboi** [comment] 2023-05-22 17:15
@nsrCodes  , @wrongsahil does requestly have any steps to run the code locally, so one could attempt fixing the issues? I am a new to open source, don't know exactly how to proceed. I am getting errors while cloning to desktop. 
`RPC failed; HTTP 400 curl 22 The requested URL returned error: 400 fatal: expected 'packfile'`

**Comment by rohanmathur91** [comment] 2023-05-22 18:23
@tarunsamanta2k20 @sashaboi The issue is related to the desktop app, since we have a common UI for both extension and desktop app the UI changes will go in [requestly repo](https://github.com/requestly/requestly). Follow these [steps](https://github.com/requestly/requestly-desktop-app#development) to setup locally.

**Comment by tarunsamanta2k20** [comment] 2023-05-22 18:25
@rohanmathur91 but while searching for some text in the desktop app then no results found but in requestly,  everything is present. Correct me if I am wrong.

**Comment by rohanmathur91** [comment] 2023-05-22 18:28
Yes, you will find all the UI stuff in requestly repo

**Comment by tarunsamanta2k20** [comment] 2023-05-22 18:36
@rohanmathur91 then how to test in local environment after changes by running the desktop app?

**Comment by tarunsamanta2k20** [comment] 2023-05-22 19:08
> @tarunsamanta2k20 @sashaboi The issue is related to the desktop app, since we have a common UI for both extension and desktop app the **UI changes will go in [requestly repo](https://github.com/requestly/requestly)**. Follow these [steps](https://github.com/requestly/requestly-desktop-app#development) to setup locally.
@rohanmathur91 this tutorial link of running server locally is not opening :
https://github.com/requestly/requestly-master/blob/master/app/README.md

**Comment by tarunsamanta2k20** [comment] 2023-05-22 19:10
@rohanmathur91 could you please write here instructions for running server locally?

**Comment by rohanmathur91** [comment] 2023-05-22 19:33
> @rohanmathur91 then how to test in local environment after changes by running the desktop app?

yes

**Comment by rohanmathur91** [comment] 2023-05-22 19:34
> @rohanmathur91 could you please write here instructions for running server locally?

Follow this [steps](https://github.com/requestly/requestly/tree/master/app#readme).

**Comment by tarunsamanta2k20** [comment] 2023-05-25 21:30
@echo-sg I don't have minimum hardware for running your ap. Assign it to someone else.

**Comment by Toshikas** [comment] 2023-05-26 07:10
Hi @rohanmathur91 ,
I would like to work on this issue. Feel free to assign this issue to me.

**Closed** 2023-05-29 06:45 UTC
Labels: bug, good first issue
